<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>RRYautja</RootNamespace>
    <AssemblyName>RRYautja</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>..\..\Assemblies\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <Optimize>true</Optimize>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <Optimize>false</Optimize>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Xenomorph\Hives\Class1.cs" />
    <Compile Remove="Xenomorph\Hives\HiveGrid.cs" />
    <Compile Remove="Xenomorph\Jobstuff\Drivers\TunnelHiveLikeSpawner.cs" />
    <Compile Remove="Xenomorph\XenoGetPawnThing.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AlienRace">
      <HintPath>..\..\Assemblies\AlienRace.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Compile Include="..\AlienRaceStub\AlienRaceStub.cs" />
    <Reference Include="Thumper">
      <HintPath>..\..\Assemblies\Thumper.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4871" />
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" />
  </ItemGroup>

</Project>